### PR TITLE
Add option to show tag links on smaller viewports

### PR DESCRIPTION
**Pull request by brakkum**
Since navbar tags are hidden on smaller viewports due to Bulma, this is an option to show them elsewhere when the others are hidden, thanks to a Bulma helper class. This was kind of irking me, since Bulma's defaults would only show the tags on views greater than 1,000+ pixels. Could put the config option in info.json as well, but this seemed more like a separate file kind of situation. Also, could move the tags elsewhere, I thought under the user bio seemed good.

### CODE REVIEW

**Comment by sunfarm** [comment]
I haven't optimized (or even tested) for mobile so I'm not surprised this is messed up. I don't think anyone will ever want to not have a navigation menu on mobile so I don't think there needs to be a config option for this.

I do think introducing a config.json may be a good idea at some point though. Maybe to give an option to use a hamburger menu or something on mobile.

**Comment by brakkum** [comment]
>I haven't optimized (or even tested) for mobile so I'm not surprised this is messed up. I don't think anyone will ever want to not have a navigation menu on mobile so I don't think there needs to be a config option for this. ...

@sunfarm true, that’s probably a better way to handle it than adding a whole other box to get in the way. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sunfarm** [comment]
Looks like there are some conflicts. Also, what I was saying is that I think you change should just be hardcoded rather than configurable since as things currently are, there is no tag/nav menu on mobile.

**Comment by brakkum** [comment]
@sunfarm Got it. Fixed merge issues. I removed the nav .navbar-menu div, and put the tag.map() inside the .navbar-brand div. Same presentation as before, but doesn't auto hide items on mobile display. Maybe this is bad for accessibility though? Also, I did make it so anything past the third tag would hide on mobile, otherwise there would be unreachable tags, depending on tag text length. Because I plan too far ahead sometimes.

**Comment by sunfarm** [comment]
Looks good. Could you just remove config.json from the PR (we can add it when necessary) and I'll merge

**Comment by sunfarm** [comment]
I do want to make sure the template is highly accessible, but since I haven't really done a pass with that in mind, no need to worry about it yet.

**Comment by brakkum** [comment]
@sunfarm Done and done.

**Review by sunfarm — APPROVED** [review]
Sweet

**Pull request merged**
